### ISSUE TITLE
Set up continuous deployment with Travis

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#1]
The intermine homepage uses [hugo](https://gohugo.io/) to generate static pages. Right now we have to manually generate the pages, then copy/paste the alterations over to the master branch of [intermine.github.io](https://github.com/intermine/intermine.github.io).

**task** clone this repo and set up a deployment script with [travis](https://travis-ci.org/) to automatically build the site and push to another repo's master branch. 

When it looks like it's working locally for you, we can merge the code and tweak tokens / env variables to deploy it to the live site.

**Comment by HaoPatrick** [comment]
We can do this by adding a deploy key to the Travis env variables and after successfully built the static pages, we load the key from Travis and then push back to GitHub, am I correct?
Can I start working on it?

**Comment by yochannah** [comment]
@HaoPatrick go ahead! :+1:
