### ISSUE TITLE
Links broken in tutorial page

### ISSUE THREAD

**Issue by MinervaLong** [intermine/intermine-homepage-2017#15]
Hello @yochannah I've found that in http://intermine.org/tutorials/ the Twitter and Thalemine tutorial links give error, can I take care of it? :)

**Comment by yochannah** [comment]
thanks, please do! 

The thalemine tutorial is gone now 😭  so just remove it entirely

**Comment by MinervaLong** [comment]
Yes, I've just realized :0

**Comment by itolimaesther** [comment]
Can I also work on this too?

**Comment by Angelvicks** [comment]
Hello @yochannah can I work on this too?

**Comment by Angelvicks** [comment]
#19 I tried to fix the twitter link and remove the Thalemine link since its a dead link.

**Comment by yochannah** [comment]
Fixed in several PRs - thanks all!
