### ISSUE TITLE
add elixir RIR logo to homepage

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#16]
let's add it to the footer of the homepage, alongside the other logos on the bottom right.

Notes: 
- add it _as well_ as the ELIXIR-UK logo. 
- it should be the same size as the ELIXIR-UK logo. 
- the logo can be obtained here: https://elixir-europe.org/platforms/interoperability/rirs 
- things should still line up neatly - it might be best to move teh cambridge university logo first, then have two matched-height elixir logos next. 
- make sure to check layout for small/mobile screens as well as large screens. 

This may require some image editing. 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Pop by to say hi on [chat](http://chat.intermine.org). Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by itolimaesther** [comment]
I can also work on this too @yochannah

**Comment by Chigael** [comment]
hi @yochannah can i work on this issue

**Comment by yochannah** [comment]
Hey both - please go ahead! we'll only be able to merge one PR, but both contributions will count for Outreachy contributions :)

**Comment by Chigael** [comment]
@yochannah how can i get access to the codes

**Comment by pooja2299** [comment]
hey @yochannah can i also work on it?

**Comment by yochannah** [comment]
https://github.com/intermine/intermine-homepage-2017/blob/master/layouts/partials/footer.html this is probably the file you want! You'll also probably need to edit the css in the static folder. 

@pooja2299 you're welcome to work on this too! We'll only merge one PR, but both contributions would count for the purposes of outreachy.

**Comment by Angelvicks** [comment]
Hello @yochannah , Please can i work on it also?

**Comment by Chigael** [comment]
@yochannah thanks

**Comment by pooja2299** [comment]
@yochannah thanks

**Comment by owans** [comment]
Hi @yochannah I would also like to work on this, I have gone through the guidelines.
