### ISSUE TITLE
Make homepage mobile friendly [css/html]

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#2]
See https://github.com/intermine/bluegenes/issues/167 - we probably want to make the results table have a max width and overflow auto.

**Comment by aditodkar** [comment]
@yochannah I have installed Hugo. Can I work on this ?

**Comment by yochannah** [comment]
Go ahead! :+1:

**Comment by aditodkar** [comment]
@yochannah docs/style.less and static/style.less are same can you please explain me why so ?

**Comment by aditodkar** [comment]
@yochannah I got the solution for this issue css style of main tag should be set to `width:100%` and `overflow:auto`

I tested the website in chrome by adding `width:100%` and `overflow:auto` it works fine see below screenshot :

![screenshot_8](https://user-images.githubusercontent.com/16613832/36265940-59c2acea-1296-11e8-904c-d51ad8b72843.png)

![screenshot_4](https://user-images.githubusercontent.com/16613832/36266020-8e046a8e-1296-11e8-9aba-982158dc58e6.png)

![screenshot_7](https://user-images.githubusercontent.com/16613832/36266041-978de5da-1296-11e8-8c4c-7c46a99e1159.png)


But when I try to make same changes in main tag it does not work what could be the possible reason and throws some error (see screenshot below):

![screenshot_2](https://user-images.githubusercontent.com/16613832/36266100-bac24ed8-1296-11e8-8e1f-0ff2a9dd9d0f.png)

**Comment by yochannah** [comment]
don't worry about the error - that's happening even on live intermine.org and is probably a problem with flymine. 

The fix looks good in the screenshots, would you like to make a PR?

**Comment by yochannah** [comment]
fixed by #5
