### ISSUE TITLE
Have the Training/Tutorial portal link in Intermine home page

### ISSUE THREAD

**Issue by ddada24** [intermine/intermine-homepage-2017#29]
There can be a training/Tutorial link in the top right corner of Intermine home page, this will help a first time visitor on the site to find it easy familiarizing themselves to the page and also carry out the required activities on Intermine.

**Comment by silvinabt87** [comment]
Hi, I'd like to contribute here, if possible. I'm an Outreachy applicant and this would be my first contribution. Let me know of any more details that I need to take into account to work on this, please. I've already checked the README and CONTRIBUTION files, and forked the repo.

**Comment by yochannah** [comment]
hey both - and thanks for the suggestion! In this case, the training is in the dropdown menu and in the footer, so I think we'd rather keep the main menu uncluttered. Thanks for the thoughtful suggestion, though!
