### ISSUE TITLE
Add favicon [html]

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#3]
It would be nice to add a favicon to the homepage! We have various InterMine logos here: https://intermineorg.wordpress.com/logos/

**task** 
1. fork this repo
2. let us know you'd like to work on the issue! 
2. make the necessary changes to add a favicon to the repo
4. make a PR when you think it's ready!

It's fine to ask for help if you get stuck.

**Comment by aditodkar** [comment]
@yochannah I can see 3-4 favicon's which one should be added ?

**Comment by aditodkar** [comment]
@yochannah Ok I will do it.

**Comment by aditodkar** [comment]
@yochannah Should I create a new images folder in the repository ? So that I can specify the `src=""` of the image.

**Comment by yochannah** [comment]
sounds like a decent plan!

**Comment by NirmalKumarJoshi** [comment]
Can I work on this issue?

**Comment by aditodkar** [comment]
@NirmalKumarJoshi I have sent PR for this issue. If possible can we both discuss on how to solve https://github.com/intermine/intermine-homepage-2017/issues/4

**Comment by yochannah** [comment]
@NirmalKumarJoshi there is a PR awaiting review to fix this, so no need, but thanks!

**Comment by NirmalKumarJoshi** [comment]
Yeah sure @aditodkar . We will discuss on issuse #4

**Comment by yochannah** [comment]
fixed by #6
