### ISSUE TITLE
Make reference tracker dynamic using Zotero API [JS + AJAX]

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-homepage-2017#4]
We have a page which shows links to [InterMine publications](http://intermine.org/publications/). This page is static HTML, but it would be better if the data was fetched dynamically! 

We'd like to try using Zotero. See a short collection of InterMine papers here: https://www.zotero.org/groups/2117194/intermine/items

Zotero also has developer documentation: https://www.zotero.org/support/dev/start 

## Task: 
1. Look at the Zotero API documentation and decide how you would access the InterMine publication data
2. Comment on the issue saying you're picking it up
3. Fork the repo
4. When you're ready, make a PR! 

If you need help, mention @yochannah or drop by the InterMine chat!

**Comment by yochannah** [comment]
One implementation method might be to use BibBase rather than work directly with the API. From @vivekkrish

BibBase.org provides a way to automatically parse Zotero or Mendeley libraries and/or bibtex files and render the publications within a dynamic widget.

All instructions are available on the http://bibbase.org front page or at http://bibbase.org/help. BibBase is pretty full featured, and allows custom styling with CSS as well.

Here is an example page: https://bibbase.github.io/

**Comment by aditodkar** [comment]
@yochannah On [InterMine publications](http://intermine.org/publications/) I can see there are various publications which are displayed but as it is static HTML we needs to hardcoded am I right ? So using AJAX we have to dynamically populate this page -> http://intermine.org/publications/ whenever a new publication is published. Can I start working on it ?

**Comment by yochannah** [comment]
Correct! It's probably easier to use the plugin recommended by @vivekkrish if possible.

**Comment by aditodkar** [comment]
@yochannah Ok I will go through the plugin recommended by Vivek.

**Comment by kunal-mohta** [comment]
@yochannah Using BibBase.org might be the easier way to get the data from Zotero and display it, but it may cost you on the UI as the default data display style of BibBase might not "look good" with the existing style of the page.

**Comment by aditodkar** [comment]
@yochannah For getting publications data I am not able to get javascript snippet for HTML page which can be  just added in our page. Also I want to ask instead of search publications by specific Author can I search publications by search word intermine in bibase search here: http://bibbase.org/search it displays more publications which are not displayed here: http://intermine.org/publications/

**Comment by yochannah** [comment]
I actually implemented this a while ago and forgot to update the ticket!
