### ISSUE TITLE
Fixed: broken links in contacts section (community-calls links )

### ISSUE THREAD

**Issue by SiSousa** [intermine/intermine-homepage-2017#40]

**Comment by SiSousa** [comment]
in the website header, especifically on the contact section (contact/community calls) there was a broken link and also both the links (community-calls/developer-calls) and (community-calls/outreach-calls) were broken. Open to sugestions and advices.

**Comment by guptadiksha307** [comment]
Hi @SiSousa, I was also about to raise this issue but I think you first have to subscribe to the developer mailing list before every call. If your request is confirmed then only you are good to go :). I'm not sure though.
@yochannah am I correct?

**Comment by SiSousa** [comment]
@yochannah  @guptadiksha307 Hi, i hope you are all safe and well, so i have some questions about this issue... so to the user make a call the rule is first subscribe to the developer mailing list before call? cause when i open the homepage and click in the header/contact/community calls then i get a broken link, is it supposed to be like that?  but when i click in contact section/overview i have this:
![screen1](https://user-images.githubusercontent.com/62321835/77811560-ff039500-7079-11ea-9ec4-fc0c6a02b4a4.JPG)
the green is a reference to a broken link(intermine.orgcommunity-calls) and the red takes to the community calls page where i have this:
![screen2](https://user-images.githubusercontent.com/62321835/77811639-8224eb00-707a-11ea-8122-dd14eff78a88.JPG)
both the red titles take me to nowhere, so i have this page:
![screen3](https://user-images.githubusercontent.com/62321835/77811697-e182fb00-707a-11ea-81a2-c24283a8abc5.JPG)
So i didnt understand the rule(user first have to subscribe) or this error page was not supposed to happen? in case of it be a problem, can i keep the issue i was working? Thanks for any help, i am very glad to work in this project and want to contribute, open to sugestions and advices.
