### ISSUE TITLE
Add intermine logo to small resolution

### ISSUE THREAD

**Issue by enelesmai** [intermine/intermine-homepage-2017#58]
Hello!, I detected some improvements that could be done when the hamburger menu is shown.
1. **intermine** logo is hidden when small resolution and it could be a good idea to have it always visible.
2. Hamburger icon is too small, and is too close to the right, it could be a little bigger and with a margin.
3. Close button looks incomplete.

Could I work on these improvements? 

![image](https://user-images.githubusercontent.com/5160907/78505010-1572b600-7736-11ea-964f-450a311b08a2.png)

**Comment by yochannah** [comment]
These issues have been fixed in some recent PRs - thanks for the report @enelesmai !
