### ISSUE TITLE
Add new training portal

### ISSUE THREAD

**Issue by heralden** [intermine/intermine-homepage-2017#68]
The URL http://intermine.org/tutorials/, accessible via the navbar from *Biologists > Tutorials and Videos*, should use the new page created in https://github.com/intermine/training-portal.

It is also made with hugo, so hopefully this should be a simple matter. A git submodule might be a good approach.

Tip: Look into how http://intermine.org/imjs/ is integrated.

**Comment by uosl** [comment]
*Biologists > Tutorials and Videos* now points to http://intermine.org/training-portal/
(Each repository is hosted separately using gh-pages.)
