### ISSUE TITLE
Style the 'credits' item in footer 

### ISSUE THREAD

**Issue by KukkadapuSushma** [intermine/intermine-homepage-2017#8]
I feel the "Credits" link in the bottom right corner of footer - is very inappropriate in it's display.
So, would like to style it up if that's fine.

- Kindly assign me  : @KukkadapuSushma to proceed!

 @julie-sullivan  @yochannah 

![screenshot from 2018-03-06 19-37-17](https://user-images.githubusercontent.com/14278142/37036899-1306d4f8-2177-11e8-931e-7da850418382.png)

**Comment by yochannah** [comment]
Go ahead!

**Comment by KukkadapuSushma** [comment]
@yochannah 

Kindly review :) 
PR : https://github.com/intermine/intermine-homepage-2017/pull/10

**Comment by yochannah** [comment]
fixed by #10
