### ISSUE TITLE
Markdown syntax error

### ISSUE THREAD

**Issue by KukkadapuSushma** [intermine/intermine-homepage-2017#9]
I found a 'bug' - in the "credits page" - displayed below - At **the title "Site credits" being shown as markdown text** {..........}.

_Description_ : The markdown was like {title : "Site credits" ...... } in **credits/index.md** page, I have checked on multiple browsers to find if the problem was on my side, but it seems not to be. 
So, shall i rectify this error??? First of all, would like to know whether this issue is really valid or am I seeing something wrong!?? 

_NOTE_ : I found this discrepancy in the title even before I have started making the changes in my local repo.

![screenshot from 2018-03-06 22-04-28](https://user-images.githubusercontent.com/14278142/37045167-4c8247da-218b-11e8-9e60-f1e5af5c2b0d.png)

------------

_Screenshot_  : Existing code 

![screenshot from 2018-03-06 22-08-22](https://user-images.githubusercontent.com/14278142/37045408-e26dffaa-218b-11e8-900b-04420b4456e8.png)

----------

- Kindly assign me, if this is valid - @julie-sullivan @yochannah

**Comment by yochannah** [comment]
It looks ok on http://intermine.org/credits/ - but if you think there is an error, yes, definitely fix it!! :smile:

**Comment by KukkadapuSushma** [comment]
@yochannah -- Yes! I can see no issues on Master repo pages. That's why I am wondering whether it is bug or just some version problem -- related to my browsers!

**Comment by yochannah** [comment]
Hmmm. Let's leave this open and see what it's like after you PR for the other issue, then close this issue or fix as needed?

**Comment by KukkadapuSushma** [comment]
Yes, lemme focus on other issue #8 and raise PR! :+1:

**Comment by KukkadapuSushma** [comment]
This issue was arised due to my "hugo version" error.
Can close this, as there's no such bug! :) @yochannah
